export const WAITING_LAYOUT_REVISION = "les-da-2026-r9" as const;

export const WAITING_LAYOUT = {
  width: 1920,
  height: 1080,
  insetX: 96,
  insetY: 72,
  frame: {
    left: 96,
    right: 1824,
    top: 72,
    bottom: 1008,
  },
  corner: {
    targetArm: 64,
    targetStroke: 4,
    authoritySize: 92,
    supportDiameter: 136,
    haloBlur: 4,
    coreOpacityMin: 0.86,
    coreOpacityMax: 0.96,
    haloOpacityMin: 0.025,
    haloOpacityMax: 0.07,
    renderedWidth: 90,
    sourceWidth: 1105,
    sourceHeight: 1243,
    sourceApexX: 847,
    sourceApexY: 258,
    sourceHorizontalPixels: 660,
    sourceVerticalPixels: 799,
    sourceCoreThicknessPixels: 43,
  },
  matrix: {
    renderedWidth: 112,
    sourceWidth: 4790,
    sourceHeight: 4411,
    topRight: {
      right: 212,
      top: 96,
    },
    bottomLeft: {
      left: 212,
      bottom: 96,
    },
    driftX: 2.5,
    driftY: 2,
    topRightOpacity: 0.18,
    bottomLeftOpacity: 0.16,
    opacityAmplitude: 0.022,
  },
  rail: {
    width: 18,
    height: 200,
    dotDiameter: 3.5,
    centerSpacing: 10,
    terminalDiameter: 8,
    crossSpan: 14,
    crossStroke: 2.5,
    rightCenterY: 324,
    leftCenterY: 702,
  },
} as const;

export const WAITING_LAYOUT_DERIVED = {
  frameWidth: WAITING_LAYOUT.frame.right - WAITING_LAYOUT.frame.left,
  frameHeight: WAITING_LAYOUT.frame.bottom - WAITING_LAYOUT.frame.top,
  railLeft: WAITING_LAYOUT.frame.left - WAITING_LAYOUT.rail.width / 2,
  railRight: WAITING_LAYOUT.frame.right - WAITING_LAYOUT.rail.width / 2,
  rightRailTop: WAITING_LAYOUT.rail.rightCenterY - WAITING_LAYOUT.rail.height / 2,
  leftRailTop: WAITING_LAYOUT.rail.leftCenterY - WAITING_LAYOUT.rail.height / 2,
  railCenterDeltaY: WAITING_LAYOUT.rail.leftCenterY - WAITING_LAYOUT.rail.rightCenterY,
  cornerImageLeft: -WAITING_LAYOUT.corner.sourceApexX / WAITING_LAYOUT.corner.sourceWidth * WAITING_LAYOUT.corner.renderedWidth,
  cornerImageTop: -WAITING_LAYOUT.corner.sourceApexY / WAITING_LAYOUT.corner.sourceWidth * WAITING_LAYOUT.corner.renderedWidth,
  cornerHorizontalBranch: WAITING_LAYOUT.corner.sourceHorizontalPixels / WAITING_LAYOUT.corner.sourceWidth * WAITING_LAYOUT.corner.renderedWidth,
  cornerVerticalBranch: WAITING_LAYOUT.corner.sourceVerticalPixels / WAITING_LAYOUT.corner.sourceWidth * WAITING_LAYOUT.corner.renderedWidth,
  cornerCoreThickness: WAITING_LAYOUT.corner.sourceCoreThicknessPixels / WAITING_LAYOUT.corner.sourceWidth * WAITING_LAYOUT.corner.renderedWidth,
  matrixHeight: WAITING_LAYOUT.matrix.sourceHeight / WAITING_LAYOUT.matrix.sourceWidth * WAITING_LAYOUT.matrix.renderedWidth,
  matrixTopRightLeft: WAITING_LAYOUT.width - WAITING_LAYOUT.matrix.topRight.right - WAITING_LAYOUT.matrix.renderedWidth,
  matrixBottomLeftTop: WAITING_LAYOUT.height - WAITING_LAYOUT.matrix.bottomLeft.bottom -
    WAITING_LAYOUT.matrix.sourceHeight / WAITING_LAYOUT.matrix.sourceWidth * WAITING_LAYOUT.matrix.renderedWidth,
} as const;
